version: '3.7'

services:
  web:
    build: ./project
    command: gunicorn core.wsgi --bind 0.0.0.0:8005
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8001:8005
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  dashboard:
    build: ./project
    command:  flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery